version: '3.8'

services:
  orgaflow:
    image: orgaflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionString=Host=db;Port=5433;Database=OrgaFlowDb;Username=postgres;Password=secret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: orgaflow_postgres
    restart: always
    environment:
      POSTGRES_DB: OrgaFlowDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
