version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5095:8080"  
    networks:
      - orgaflow-net

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "5096:8080"  
    networks:
      - orgaflow-net

  main-app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: main-app
    ports:
      - "80:8080"
    depends_on:
      - auth-service
      - task-service
    networks:
      - orgaflow-net

  postgres:
    image: postgres:15
    container_name: orgaflow_postgres
    restart: always
    environment:
      POSTGRES_DB: OrgaFlowDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orgaflow-net

networks:
  orgaflow-net:
    driver: bridge

volumes:
  postgres_data:
